language: python
python:
- '2.7'
- '3.6'
env:
  global:
  - PYTHONPATH="."
script: python export_util/test/test.py
deploy:
  provider: pypi
  user: bmat
  password:
    secure: ZYO/05ekIhDSyFSe/aQb2ATgqUVeTuVdPPMA3Jpw5m0sjTXEqjvsP/HGgidct6R/ENRG69r35JKStB/dB4FoF8kebJ1B81ZATb+NPC74cQgoGIAnsl/sjSX3ZeiUX7EOBQQ7RvSythiIo2JTQjAXZc7wx/xGOR4cTUv2YPSTVgX0981XuFGL4aLdWX+3IS+IlRhtfqMY6Vauh7ZhviRpFc6ODd4+zWyy4ma6VxZJfxqLZ1kYikMNYJDnOd+nZY58AGnIEc6NujvryP3t2f1eODbauBoEPbDVtnNBx/umNZeNM7sSCkwNZwGH5qoW9Vuj6onPQMRBdGensIpcTiJSSBpvu6tN2Xfvn4sbRTFcvwZWcAlHDBAHlRCF/V1zYpoyiyB5r4hhNa9RlRSq3f6+xDE4AskKkj4Voo1yV4vx9RnCpnMlixmcRr2JDUfHZpWY5RvfYmpzPPChqDwXbhDK/iuEFDFMfhd3Q0NzgYcuCSQZl5UTQbu0F1oZpgeDOiJLMTkzyhEQst1PUSu2eZHhfXCh86DyClVjBjgus4eXZvreuzls9WH6UZ7dUQf/1Rhc91yrBgzI3wMelSMRyZkM4p94cJ0yD72LTQf9AIx1p8qDLgsn6ZklOR7MPDEkvOoDCXT2U4a63Wk4XONbI1vpWRKsPqeBf58tEnxO+dFPl/c=
  distributions: bdist_wheel
  on:
    tags: true
